# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Symmetry Workshop - ICLR 2022
tagline: Symmetry and equivariance in learning algorithms and data
email: symmetryworkshop@protonmail.com
github_username: symmetryworkshop
description: Symmetry and equivariance are fundamental to the success of deep learning. In the last few years, encoding symmetry information in neural architectures, in most cases in the form of constructing equivariant networks, has become a key design principle when designing efficient neural networks for structured and complex data. In parallel, symmetry is ubiquitous in science, not only in crystallography and quantum theory, where its role has long been explicitly recognized, but also in chemistry, biology, and others. Unfortunately, symmetry and equivariance are often studied by different communities in isolation, missing out on fruitful synergies and interactions. This workshop aims to bring together researchers at the forefront of symmetry and equivariance from machine learning, statistics, mathematics, and the broader scientific community. The goal of the workshop is to nurture the community of researchers working at the intersection of deep learning, representation theory, and physical science areas, by providing a platform to share ideas from diverse fields and shape the vision of the rapidly growing field of symmetry and equivariance.
author: The Symmetry Workshop - ICLR 2022
baseurl: ""
url: ""
logo: 
favicon: 

# Reading Files
include:
  - _pages

# Collections
collections:
  playground:
    output: true
    permalink: /:collection/:path/
#   collection2:
#     output: true
#     permalink: /:collection/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      hero_image: ./assets/img/plant.png

# defaults:
#   - scope:
#       path: ""
#       type: "collection1"
#     values:
#       layout: "page"
#   - scope:
#       path: ""
#       type: "collection1"
#     values:
#       layout: "page"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag 

# Theme: Bulma Clean Theme
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

